flowchart LR
lb[LB] --> api1(API) & api2(API) --push--> q1
subgraph c1 [ECS cluster]
    api1
    api2
end
q1[job queue] --pull--> w1[Worker] & w2[Worker]
subgraph c2 [ECS auto scaling cluster]
    w1
    w2
end