name: Destroy application infrastructure

on:
  workflow_dispatch:
    inputs:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ECR: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com"

jobs:

  provision:
    name: Terraform destroy
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:

    - name: Create resources
      working-directory: infrastructure
      run: |
          terraform init -backend-config="bucket=$AWS_ACCOUNT_ID-terraform-state"
          terraform destroy -auto-approve

    